#!/usr/bin/env python3

# This script will take a Discogs release identifier and gather track data from Discogs to 
# generate a Label track text file for Audacity. Post recording of vinyl record, one can
# import the label track text file to get the tracks labeled and the markers close to where
# they should be.

# Written by Karl Abbott <karl1@99b.org>
# Licensed under the GPL version 3.

import sys,subprocess,json,urllib.parse,datetime


try:
	f=open("audiscogs.conf","r")
except:
	f=open("audiscogs.conf","w")
	f.write('discogs_token="<Your access token>"\n')
	f.close()
	print("Please edit audiscogs.conf and provide a Discogs Access Token.")
	sys.exit(1)

discogs_token=None

for line in f:
	line=line.strip("\n").split("discogs_token=")
	if len(line)>1:
		discogs_token=line[1].strip('"').strip("'")

f.close()

if discogs_token==None or discogs_token=="<Your access token>":
	print("Please edit audiscogs.conf and provide a Valid Discogs Access Token.")
	print("To re-generate audiscogs.conf, delete the current file and re-run audiscogs.")
	sys.exit(1)


def xml_scrub(textin):
	newtext=""
	for line in textin.split("\n"):
		start=line.find('<')
		end=line.find('>')
		if start>-1 and end>-1:
			url=line[start+1:end]
			line=line.replace('<'+url+'>','['+url+']('+url+')')
		line=line.replace('<','&lt;')
		line=line.replace('>','&gt;')
		line=line.replace('&','&amp;')
		newtext=newtext+line
	return newtext

if len(sys.argv[1:])==0:
	print("audiscogs")
	print("")
	print("Usage: ")
	print("")
	print("audiscogs <Discogs Release ID>")
	print("")
	print("A Discogs Release ID is the integer in this type of Discogs URL with the word release in it:")
	print("")
	print("https://www.discogs.com/Ben-Folds-Five-Ben-Folds-Five-Live/release/4722337")
	print("")
	sys.exit(1)

music_id=sys.argv[1:][0]
release_id=urllib.parse.quote(music_id,safe='')

# grab the id and then query the release....
myrelease=subprocess.getoutput('curl -s "https://api.discogs.com/releases/'+str(release_id)+'" -H "Authorization: Discogs token='+discogs_token+'"')
myrelease_json=json.loads(myrelease)
x=0
for genre in myrelease_json["genres"]:
	if x==0:
		my_genre=genre
	x=x+1
x=0
for artist in myrelease_json["artists"]:
	if x==0:
		artist_name=artist["name"]
	x=x+1


file_tag=artist_name.replace("'","").replace(' ','_').replace("/","-")+myrelease_json["title"].replace("'","").replace(' ','_').replace("/","-")[0:10]+"-"
print("Writing out "+str(file_tag+music_id)+"-tags.xml for importing into metadata.")
tags_out=open(file_tag+music_id+"-tags.xml","w")
tags_out.write("<tags>\n")
tags_out.write('\t<tag name="GENRE" value="'+xml_scrub(my_genre)+'"/>\n')
try:
	tags_out.write('\t<tag name="YEAR" value="'+xml_scrub(myrelease_json["released"])+'"/>\n')
except:
	tags_out.write('\t<tag name="YEAR" value=""/>\n')
tags_out.write('\t<tag name="ARTIST" value="'+xml_scrub(artist_name)+'"/>\n')
tags_out.write('\t<tag name="ALBUM" value="'+xml_scrub(myrelease_json["title"])+'"/>\n')
tags_out.write("</tags>\n")
tags_out.close()

# Parse the track list.
tracklist=myrelease_json['tracklist']
track_counter=datetime.timedelta(hours=0,minutes=0,seconds=0)
# These two lines format the counter the way that audacity needs it
# May need to not do time but do everything as a datetime...
track_counter_float=float(track_counter.total_seconds())
tcstring=str(f'{track_counter_float:.6f}')

print("Writing out "+str(file_tag+music_id)+"-label.txt for importing as a label track.")
lf=open(str(file_tag+music_id)+"-label.txt","w")

# Let's generate the label file now..
for track in tracklist:
	lf.write(tcstring+"\t"+tcstring+"\t"+track["title"]+"\n")
	if len(track["duration"])==0:
		track["duration"]="05:00"
	duration=datetime.datetime.strptime(track["duration"],"%M:%S").time()
	track_counter_increment=datetime.timedelta(hours=duration.hour,minutes=duration.minute,seconds=duration.second)
	track_counter=track_counter+track_counter_increment
	track_counter_float=float(track_counter.total_seconds())
	tcstring=str(f'{track_counter_float:.6f}')

lf.close()
